#!/usr/bin/env php
<?php

if(file_exists(__DIR__ . '/../../autoload.php')) {
  require __DIR__ . '/../../autoload.php';
} else {
  require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Kirby CLI', '1.0.0');
$app->add(new Kirby\Cli\InstallCommand());
$app->add(new Kirby\Cli\InstallCoreCommand());
$app->add(new Kirby\Cli\InstallPanelCommand());
$app->add(new Kirby\Cli\InstallIndexCommand());
$app->add(new Kirby\Cli\InstallHtaccessCommand());
$app->add(new Kirby\Cli\UpdateCommand());
$app->add(new Kirby\Cli\ClearCacheCommand());
$app->add(new Kirby\Cli\ClearThumbsCommand());
$app->add(new Kirby\Cli\MakeControllerCommand());
$app->add(new Kirby\Cli\MakeBlueprintCommand());
$app->add(new Kirby\Cli\MakeSnippetCommand());
$app->add(new Kirby\Cli\MakeTemplateCommand());
$app->add(new Kirby\Cli\MakeUserCommand());
$app->run();