#!/usr/bin/env php
<?php

if(file_exists(__DIR__ . '/../../autoload.php')) {
  require __DIR__ . '/../../autoload.php';
} else {
  require __DIR__ . '/vendor/autoload.php';
}

ini_set('display_errors', 1);

$app = new Symfony\Component\Console\Application('Kirby CLI', '1.5.0');

// Install Commands
$app->add(new Kirby\Cli\Command\Install());
$app->add(new Kirby\Cli\Command\Install\Core());
$app->add(new Kirby\Cli\Command\Install\Panel());
$app->add(new Kirby\Cli\Command\Install\Toolkit());
$app->add(new Kirby\Cli\Command\Install\Index());
$app->add(new Kirby\Cli\Command\Install\Htaccess());

// Uninstall Commands
$app->add(new Kirby\Cli\Command\Uninstall\Panel());

// Update Command
$app->add(new Kirby\Cli\Command\Update());

// Clear Commands 
$app->add(new Kirby\Cli\Command\Clear\Cache());
$app->add(new Kirby\Cli\Command\Clear\Thumbs());

// Make Commands
$app->add(new Kirby\Cli\Command\Make\Controller());
$app->add(new Kirby\Cli\Command\Make\Snippet());
$app->add(new Kirby\Cli\Command\Make\Template());
$app->add(new Kirby\Cli\Command\Make\Blueprint());
$app->add(new Kirby\Cli\Command\Make\User());
$app->add(new Kirby\Cli\Command\Make\Tag());
$app->add(new Kirby\Cli\Command\Make\Plugin());

// Plugin Commands
$app->add(new Kirby\Cli\Command\Plugin\Install());
$app->add(new Kirby\Cli\Command\Plugin\Uninstall());
$app->add(new Kirby\Cli\Command\Plugin\Update());

// Kirby Version
$app->add(new Kirby\Cli\Command\Version());

$app->run();